
#ifndef CHEAPHOTELSHOWER_EXPORT_H
#define CHEAPHOTELSHOWER_EXPORT_H

#ifdef CHEAPHOTELSHOWER_STATIC_DEFINE
#define CHEAPHOTELSHOWER_EXPORT
#define CHEAPHOTELSHOWER_NO_EXPORT
#else
#ifndef CHEAPHOTELSHOWER_EXPORT
#ifdef CheapHotelShower_EXPORTS
/* We are building this library */
#define CHEAPHOTELSHOWER_EXPORT __declspec(dllexport)
#else
/* We are using this library */
#define CHEAPHOTELSHOWER_EXPORT __declspec(dllimport)
#endif
#endif

#ifndef CHEAPHOTELSHOWER_NO_EXPORT
#define CHEAPHOTELSHOWER_NO_EXPORT
#endif
#endif

#ifndef CHEAPHOTELSHOWER_DEPRECATED
#define CHEAPHOTELSHOWER_DEPRECATED __declspec(deprecated)
#endif

#ifndef CHEAPHOTELSHOWER_DEPRECATED_EXPORT
#define CHEAPHOTELSHOWER_DEPRECATED_EXPORT                                     \
  CHEAPHOTELSHOWER_EXPORT CHEAPHOTELSHOWER_DEPRECATED
#endif

#ifndef CHEAPHOTELSHOWER_DEPRECATED_NO_EXPORT
#define CHEAPHOTELSHOWER_DEPRECATED_NO_EXPORT                                  \
  CHEAPHOTELSHOWER_NO_EXPORT CHEAPHOTELSHOWER_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#ifndef CHEAPHOTELSHOWER_NO_DEPRECATED
#define CHEAPHOTELSHOWER_NO_DEPRECATED
#endif
#endif

#endif /* CHEAPHOTELSHOWER_EXPORT_H */
